image: python:latest

stages:
  - lint
  - test

before_script:
  - pip install poetry
  - poetry install --no-root

lint:
  stage: lint
  script:
    - poetry run ruff check
    - poetry run ruff format --check
    - poetry run mypy .

test:
  stage: test
  script:
    - poetry run pytest -v --cov=. --cov-report=xml
  after_script:
    - bash <(curl -s https://codecov.io/bash)
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
