image: python:latest

stages:
  - lint

before_script:
  - pip install poetry
  - poetry install --no-root

lint:
  stage: lint
  script:
    - poetry run ruff check
    - poetry run ruff format --check
    - poetry run mypy .
