image: ghcr.io/astral-sh/uv:0.6-python3.13-bookworm

stages:
  - lint
  - test
  - deploy

lint:
  stage: lint
  script:
    - uv run ruff check
    - uv run ruff format --check
    - uv run mypy .

test:
  stage: test
  script:
    - uv run pytest

deploy_to_gitlab:
  stage: deploy
  needs:
    - test
  only:
    refs:
      - master
  except:
    - tags
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login registry.gitlab.com -u $GITLAB_USERNAME -p $GITLAB_PASSWORD
    - docker buildx create --use
  script:
    - docker buildx build --push --tag registry.gitlab.com/rogs/cleanmedia:latest .
