name: CI

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Run Ruff & Mypy
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv run ruff check
          uv run ruff format --check
          uv run mypy .

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Run Tests
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv run pytest -v --cov=. --cov-report=xml

      - name: Upload to Codecov
        run: bash <(curl -s https://codecov.io/bash)

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Log in to Gitea Registry
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login git.rogs.me -u rogs --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push image
        run: |
          docker buildx build --push \
            --tag rogsme/cleanmedia:latest \
            --tag git.rogs.me/rogs/cleanmedia:latest \
            .
