name: CI

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Run Ruff & Mypy
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv run ruff check
          uv run ruff format --check
          uv run mypy .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Run Tests
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv run pytest -v --cov=. --cov-report=xml

      - name: Upload to Codecov
        run: bash <(curl -s https://codecov.io/bash)
