name: CI

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:0.6-python3.13-bookworm
    steps:
      - uses: actions/checkout@v3
      - name: Run Ruff & Mypy
        run: |
          uv run ruff check
          uv run ruff format --check
          uv run mypy .

  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:0.6-python3.13-bookworm
    steps:
      - uses: actions/checkout@v3
      - name: Run Pytest
        run: |
          uv run pytest -v --cov=. --cov-report=xml
      - name: Upload to Codecov
        run: bash <(curl -s https://codecov.io/bash)
